apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cicd-bookinfo
  namespace: cicd-bookinfo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: cicd-bookinfo
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: cicd-bookinfo
      server: "https://kubernetes.default.svc"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "git@github.com:generalpax/ci-cd-istio-tekton.git"
---
apiVersion: v1
kind: Secret
metadata:
  name: cicd-bookinfo-repo-creds
  namespace: cicd-bookinfo
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: git@github.com:generalpax/ci-cd-istio-tekton.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...
    -----END OPENSSH PRIVATE KEY-----
