apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: task-cicd-bookinfo-git-clone
spec:
  taskRef:
    name: git-clone
  params:
    - name: GIT_URL
      value: https://github.com/generalpax/ci-cd-istio-tekton
    - name: REVISION
      value: master
